import = ["/home/ondra/.config/alacritty/themes/hyper.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "NotoSansM Nerd Font"
style = "Regular"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
#gtk_theme_variant = "None"
opacity = 0.8
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
